# Constants
INPUT_SHAPE = (28, 28, 1)
OUTPUT_SHAPE = (28, 28, 1)

DISPLAY_ROW = 5
DISPLAY_COLUMN = 5

TOTAL_TRAINING_ROUND = 50
TRAINING_EPOCHS = 256
BATCH_SIZE = 32

TEXT_2_IMAGE_DATASET_PATH = 'data/eng.txt'
FACE_IMAGE_DATASET_PATH = 'data/face'
